// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://optwwgaiyunblewodqmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wdHd3Z2FpeXVuYmxld29kcW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDE0NzgsImV4cCI6MjA2ODc3NzQ3OH0.mE5Eg2UKH9GHzisEh2NUOUivrgoluHpRwDjos6vPtZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});